name: Sync package to AUR

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Save ssh key
        run: |
          echo ${{ secrets.AUR_SSH_KEY }} | install -Dm400 /dev/stdin ~/.ssh/id_ed25519

      - name: Install and configure git
        run: |
          sudo apt-get install git

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Sync packages to AUR
        run: |
          set -x
          for i in $(git show --pretty="" --name-only | cut -d/ -f1 | sort -u)
          do
            [ ! -d $i ] && continue
            [ ${i:0:1} = . ] && continue

            cd ${GITHUB_WORKSPACE}
            git format-patch --stdout HEAD~1 -- $i > ~/$i.patch

            rm -rf ~/$i
            [ -n "${{ secrets.READ_ONLY }}" ] && git clone https://aur.archlinux.org/$i.git ~/$i || git clone ssh://aur@aur.archlinux.org/$i.git ~/$i

            cd ~/$i
            git config user.name $(cat ~/$i.patch | sed -n '/^From:.*>$/{s/^From: \(.*\) <\(.*\)>$/\1/;p}')
            git config user.email $(cat ~/$i.patch | sed -n '/^From:.*>$/{s/^From: \(.*\) <\(.*\)>$/\2/;p}')
            git am -p2 ~/$i.patch;
            [ -n "${{ secrets.READ_ONLY }}" ] && git show || git push origin master
          done
